CREATE TABLE [dbo].[Errors]
(
	[Code] INT NOT NULL PRIMARY KEY UNIQUE,
    [Type] NCHAR(256) NOT NULL, 
    [Phrase] NVARCHAR(256) NOT NULL, 
    [Message] NVARCHAR(256) NOT NULL,
    [WillAutoAssign] NVARCHAR(256) NOT NULL
)
